# Generated by Django 2.0.13 on 2020-03-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubdate', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=1000)),
                ('media', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('link', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
            ],
        ),
    ]
